version: '3'

services:

  mysql-development:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
    ports:
      - "3308:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  tomcat:
    build: deploy
    ports:
      - "85:8080"
